import React, { useState, useCallback } from 'react';
import { generateLifeReport, API_KEY_ERROR } from './services/geminiService';
import { InputForm } from './components/InputForm';
import { ReportDisplay } from './components/ReportDisplay';
import { Loader } from './components/Loader';
import { UserInput } from './types';

const App: React.FC = () => {
  const [userInput, setUserInput] = useState<UserInput>({
    name: '',
    dob: '',
    country: 'India',
  });
  const [report, setReport] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateReport = useCallback(async () => {
    if (!userInput.name || !userInput.dob || !userInput.country) {
      setError('Please fill in all the fields.');
      return;
    }
    setIsLoading(true);
    setError(null);
    setReport(null);

    try {
      const generatedReport = await generateLifeReport(userInput);
      
      if (generatedReport === API_KEY_ERROR) {
        setError("API Key नहीं मिली। कृपया ब्राउज़र का डेवलपर कंसोल (F12 दबाएँ) खोलकर देखें कि क्या कोई 'DEBUG' मैसेज दिख रहा है। सुनिश्चित करें कि आपने 'Secrets' टैब में API_KEY सही से डाली है और ऐप को रीस्टार्ट किया है।");
      } else {
        setReport(generatedReport);
      }
    } catch (err) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError('An unknown error occurred while generating the report. Please try again.');
      }
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  }, [userInput]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-slate-900 text-white p-4 sm:p-6 lg:p-8 font-sans">
      <div className="max-w-4xl mx-auto">
        <header className="text-center my-8">
          <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-indigo-400">
            AI LifeTime Analyzer
          </h1>
          <p className="mt-4 text-lg text-gray-300">
            Turn your date of birth into your life’s magical timeline! 🌟
          </p>
        </header>

        <main>
          <div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-2xl p-6 sm:p-8 shadow-2xl shadow-purple-500/10">
            <InputForm
              userInput={userInput}
              setUserInput={setUserInput}
              onSubmit={handleGenerateReport}
              isLoading={isLoading}
            />
          </div>

          <div className="mt-8">
            {isLoading && <Loader />}
            {error && (
              <div className="bg-red-900/50 border border-red-700 text-red-300 p-4 rounded-lg text-center space-y-4">
                <p className="font-semibold">Oops! Something went wrong.</p>
                <p className="text-sm">{error}</p>
                <button
                  onClick={handleGenerateReport}
                  className="bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-lg transition-colors duration-300"
                >
                  Try Again
                </button>
              </div>
            )}
            {report && <ReportDisplay content={report} />}
            {!isLoading && !report && !error && (
                <div className="text-center text-gray-400 py-10">
                    <p>Enter your details above to reveal your life's story.</p>
                </div>
            )}
          </div>
        </main>

        <footer className="text-center py-8 text-gray-500 text-sm">
            <p>Generated by AI. For entertainment purposes only.</p>
        </footer>
      </div>
    </div>
  );
};

export default App;